{% set name = "python-jose" %}
{% set version = "3.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-jose-{{ version }}.tar.gz
  sha256: 55779b5e6ad599c6336191246e95eb2293a9ddebd555f796a65f838f07e5d78a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - pytest-runner
  run:
    - cryptography
    - python >=3.6
    - ecdsa !=0.15
    - pyasn1
    - python
    - rsa

test:
  files:
    - usage.py
  source_files:
    - tests
  commands:
    - pip check
    - python usage.py
    - pytest -m "not (pycryptodome or pycrypto or backend_compatibility)" tests
  requires:
    - pip
    - pytest
  imports:
    - jose
    - jose.backends

about:
  home: http://github.com/mpdavis/python-jose
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: JOSE implementation in Python
  doc_url: https://python-jose.readthedocs.io
  dev_url: https://github.com/mpdavis/python-jose

extra:
  recipe-maintainers:
    - mariusvniekerk
    - dgasmith
    - swainn
