{% set name = "python-jose" %}
{% set version = "3.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8484b7fdb6962e9d242cce7680469ecf92bda95d10bbcbbeb560cacdff3abfce

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - cryptography
    - future <1.0
    - python
    - six <2.0
    - ecdsa
    - pyasn1
    - rsa

test:
  files:
    - usage.py
  source_files:
    - tests
  commands:
    - python usage.py
    - pytest -m "not (pycryptodome or pycrypto or backend_compatibility)" tests
    - pip check
  requires:
    - pytest
    - pip
  imports:
    - jose
    - jose.backends

about:
  home: http://github.com/mpdavis/python-jose
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: JOSE implementation in Python
  doc_url: https://python-jose.readthedocs.io
  dev_url: https://github.com/mpdavis/python-jose

extra:
  recipe-maintainers:
    - mariusvniekerk
