{% set name = "python-jose" %}
{% set version = "3.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/python-jose-{{ version }}.tar.gz
  sha256: 9a9a40f418ced8ecaf7e3b28d69887ceaa76adad3bcaa6dae0d9e596fec1d680

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - pytest-runner
  run:
    - python >={{ python_min }}
    - cryptography >=3.4.0
    - ecdsa !=0.15
    - rsa >=4.0, <5.0, !=4.4, !=4.1.1
    - pyasn1 >=0.4.1, <0.5.0

test:
  files:
    - usage.py
  source_files:
    - tests
  commands:
    - pip check
    - python usage.py
    - pytest -m "not (pycryptodome or pycrypto or backend_compatibility)" tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  imports:
    - jose
    - jose.backends

about:
  home: http://github.com/mpdavis/python-jose
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: JOSE implementation in Python
  doc_url: https://python-jose.readthedocs.io
  dev_url: https://github.com/mpdavis/python-jose

extra:
  recipe-maintainers:
    - mariusvniekerk
    - dgasmith
    - swainn
